### ISSUE TITLE
update webpack to 3.x

### ISSUE THREAD

**Issue by pravi** [DmitryBaranovskiy/raphael#1092]
We'd like to use webpack 3 to build raphael in debian. Please update webpack dependency to 3.x. Currently I get the following failures.

```
$ webpack && webpack --min && webpack --no-deps && webpack --no-deps --min
/usr/lib/nodejs/webpack/lib/BannerPlugin.js:19
			throw new Error("BannerPlugin only takes one argument (pass an options object)");
			^

Error: BannerPlugin only takes one argument (pass an options object)
    at new BannerPlugin (/usr/lib/nodejs/webpack/lib/BannerPlugin.js:19:10)
    at Object.<anonymous> (/home/pravi/forge/debian/git/pkg-javascript/node-raphael/webpack.config.js:9:2)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at requireConfig (/usr/lib/nodejs/webpack/bin/convert-argv.js:97:18)
```

**Comment by pravi** [comment]
#1093 fixes this

**Comment by tomasAlabes** [comment]
Already using webpack 4. Thank you fo the PR anyway!
